#!/bin/bash

export OSRM_BASE_URL_BANGKOK="${OSRM_BASE_URL_BANGKOK:-http://127.0.0.1:5007}"
export OSRM_BASE_URL_BK="${OSRM_BASE_URL_BK:-$OSRM_BASE_URL_BANGKOK}"
# Backward-compatible aliases for workbooks/envs that still say Thailand.
export OSRM_BASE_URL_THAILAND="${OSRM_BASE_URL_THAILAND:-$OSRM_BASE_URL_BANGKOK}"
export OSRM_BASE_URL_THAILAND_BANGKOK="${OSRM_BASE_URL_THAILAND_BANGKOK:-$OSRM_BASE_URL_BANGKOK}"
