#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
LOCAL_ENV_FILE="$ROOT_DIR/ops/env/local.env"
if [ -f "$LOCAL_ENV_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$LOCAL_ENV_FILE"
  set +a
fi

cd "$ROOT_DIR/apps/backend"

DEFAULT_BRP_PYTHON="/opt/anaconda3/envs/brp/bin/python"
if [ -z "${BACKEND_PYTHON:-}" ] && [ -x "$DEFAULT_BRP_PYTHON" ]; then
  BACKEND_PYTHON="$DEFAULT_BRP_PYTHON"
else
  BACKEND_PYTHON="${BACKEND_PYTHON:-python3}"
fi
BRP_BACKEND_HOST="${BRP_BACKEND_HOST:-127.0.0.1}"
BRP_BACKEND_PORT="${BRP_BACKEND_PORT:-8001}"
BRP_BACKEND_JOBS_DIR="${BRP_BACKEND_JOBS_DIR:-$ROOT_DIR/state/jobs}"
BRP_SIDE_TOOLS_DIR="${BRP_SIDE_TOOLS_DIR:-$ROOT_DIR/state/side_tools}"
BRP_CLIENT_CACHE_DIR="${BRP_CLIENT_CACHE_DIR:-$ROOT_DIR/apps/client/cache}"
BRP_BACKEND_CACHE_DIR="${BRP_BACKEND_CACHE_DIR:-$ROOT_DIR/apps/backend/cache}"
mkdir -p "$BRP_BACKEND_JOBS_DIR" "$BRP_SIDE_TOOLS_DIR" "$BRP_CLIENT_CACHE_DIR" "$BRP_BACKEND_CACHE_DIR"

BRP_BACKEND_UVICORN_WORKERS="${BRP_BACKEND_UVICORN_WORKERS:-1}"
uvicorn_args=(api_app:app --host "$BRP_BACKEND_HOST" --port "$BRP_BACKEND_PORT")
if [ "$BRP_BACKEND_UVICORN_WORKERS" != "1" ]; then
  uvicorn_args+=(--workers "$BRP_BACKEND_UVICORN_WORKERS")
fi

echo "Starting BRP FastAPI backend on http://$BRP_BACKEND_HOST:$BRP_BACKEND_PORT with $BRP_BACKEND_UVICORN_WORKERS worker(s)"
exec env BRP_BACKEND_HOST="$BRP_BACKEND_HOST" BRP_BACKEND_PORT="$BRP_BACKEND_PORT" BRP_BACKEND_JOBS_DIR="$BRP_BACKEND_JOBS_DIR" BRP_SIDE_TOOLS_DIR="$BRP_SIDE_TOOLS_DIR" BRP_CLIENT_CACHE_DIR="$BRP_CLIENT_CACHE_DIR" BRP_BACKEND_CACHE_DIR="$BRP_BACKEND_CACHE_DIR" "$BACKEND_PYTHON" -m uvicorn "${uvicorn_args[@]}"
